  function createPlayer() {
    const maxHealth = 100 + playerUpgrades.core * 5;
    const maxEnergy = 100 + playerUpgrades.charge * 10;
    const activeSkin = getSelectedSkin();
    return {
      id: "player",
      name: "Viajante",
      x: WORLD_SIZE / 2,
      y: WORLD_SIZE / 2,
      vx: 0,
      vy: 0,
      radius: 18,
      hue: activeSkin.hue < 0 ? 188 : activeSkin.hue,
      skinId: activeSkin.id,
      skin: activeSkin,
      skinGlow: activeSkin.glowIntensity,
      skinTrail: activeSkin.trailWidth,
      health: maxHealth,
      maxHealth,
      energy: maxEnergy,
      maxEnergy,
      score: 0,
      kills: 0,
      combo: 0,
      comboTimer: 0,
      phasing: false,
      phase: null,
      cooldown: 0,
      hitTimer: 0,
      trailDamage: 34,
      ribbonLife: 0.62,
      trailLinger: 0.06,
      cooldownScale: 1 - playerUpgrades.calibration * 0.08,
      pickupRadius: playerUpgrades.collection * 5,
      shellDefense: 1,
      siphon: false,
      killRestore: false,
      phaseSpeed: 430,
      phaseDrain: 29,
      arrivalNova: false,
      arrivalGuard: 0,
      moteHealing: false,
      healScale: 1,
      chainDamage: false,
      chainCombo: 0,
      chainTimer: 0,
      ghostWall: false,
      ghostWallUsed: false,
      vortexPull: false,
      reversal: false,
      dualPhase: false,
      dualPhaseCharges: 0,
      dualPhaseUsed: 0,
      activeSynergies: [],
      ribbonWidthBonus: 1,
      ribbonLingerDamageBonus: 1,
      killRestoreHealBonus: 1,
      siphonBonus: 1,
      novaRadiusBonus: 1,
      vortexPullBonus: 1,
      chainWindow: 2,
      chainMaxStacks: 5,
      phasePickupBonus: 1,
      ghostwallNova: false,
      scoreMultiplier: 1,
      berserkerBonus: 1,
      silenced: false,
      silencedTimer: 0,
      silencePermanent: false,
      silenceSnapshot: null,
      mutationBaseline: null,
      damageDebuff: 1,
      mutations: [],
      nextMutationIndex: 0
    };
  }

